name: Parabank UI Automation Execution (Headed)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create Artifact Directory
        run: mkdir -p screenshots

      - name: Install System Dependencies for Headed Mode
        # Removed libgconf-2-4 as it is deprecated in Ubuntu 24.04
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxi6 libnss3 libxss1 libasound2t64 libgbm1

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Selenium Tests in Virtual Display
        # xvfb-run provides the 'Display' that allows Headed mode to function
        run: xvfb-run --auto-servernum python -m unittest discover -s tests -p 'test_*.py'
        env:
          PYTHONPATH: . 

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: execution-artifacts
          path: screenshots/
